service: spotify-cover-automation

configValidationMode: warn

provider:
  name: aws
  stage: prod
  runtime: python3.12
  region: eu-west-1

package:
  patterns:
    - "!node_modules/**"
    - "!serverless_deployment/**"
    - "!assets/**"
    - "!tests/**"

custom:
  s3Sync:
    - bucketName: spotify.antoinedelia.fr
      localDir: web

functions:
  cover_automation:
    handler: src/main.lambda_handler
    name: spotify-cover-automation
    timeout: 29
    maximumRetryAttempts: 1
    events:
      - http:
          path: /spotify/cover-automation
          method: post
          cors:
            headers:
              - '*'
  get_playlists:
    handler: src/handlers/get_playlists.lambda_handler
    name: ${self:service}-${sls:stage}-get_playlists
    timeout: 29
    maximumRetryAttempts: 1
    events:
      - http:
          path: /spotify-cover-automation/playlists
          method: get
          cors:
            headers:
              - '*'

plugins:
  - serverless-python-requirements
  - serverless-s3-sync
